-- phpMyAdmin SQL Dump
-- version 4.1.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Giu 30, 2016 alle 13:43
-- Versione del server: 5.6.29-log
-- PHP Version: 5.3.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `my_projectalunnicalcaterra`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `assistenza`
--

CREATE TABLE IF NOT EXISTS `assistenza` (
  `id` int(11) NOT NULL,
  `id_categoria` varchar(20) NOT NULL,
  `categoria` varchar(30) NOT NULL,
  `sotto_categoria` varchar(30) NOT NULL,
  `gruppo` mediumtext NOT NULL,
  `titolo` varchar(50) NOT NULL,
  `descrizione` longtext CHARACTER SET utf8mb4 NOT NULL,
  `Highlights` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `assistenza`
--

INSERT INTO `assistenza` (`id`, `id_categoria`, `categoria`, `sotto_categoria`, `gruppo`, `titolo`, `descrizione`, `Highlights`) VALUES
(1, 'configurazione', 'Supporto tecnico', 'Smartphone e Tablet', 'Servizi per e dal tuo smartphone', 'Assistenza tecnica specializzata', '<h5>SOSsmartphone e'' il servizio di TIM per tutti i clienti, Ricaricabili o con Abbonamento, che permette di ricevere un''assistenza tecnica specializzata e personalizzata per la gestione del proprio smartphone o tablet.<br><br>\r\n\r\nGrazie al servizio SOSsmartphone potrai parlare con un esperto che ti fornira'' tutta la consulenza e l''assistenza "premium" di cui necessiti e che soprattutto sara'' in grado di connettersi in remoto ed operare direttamente sul tuo dispositivo.<br><br>\r\n\r\nPer richiedere il servizio SOSsmartphone potrai:<br><br>\r\n\r\ncontattare il numero 0458214811 (chiamata a pagamento in base al proprio piano tariffario/offerta);<br>\r\nscaricare l''App SOS Smartphone da APP Store (per iOS) e Google Play (per Android) e richiedere l''intervento.\r\n</h5>', 1),
(2, 'configurazione', 'Supporto tecnico', 'Smartphone e Tablet', 'Servizi per e dal tuo smartphone', 'Assistenza coupon', '<h5>Vuoi un nuovo smartphone?<br><br>\r\n\r\n\r\nPortaci il tuo vecchio telefono, da oggi vale uno sconto sul nuovo!<br><br>\r\n\r\n\r\nCon il servizio TIM Valuta puoi far valutare gratuitamente e senza impegno il tuo telefonino, smartphone o tablet.  Ricevi subito uno sconto da utilizzare come meglio desideri: per l''acquisto di un nuovo telefonino, smartphone, tablet, chiavetta, Internet Pack, oppure in Ricarica telefonica TIM. Il servizio e'' aperto a tutti!</h5>', 0),
(3, 'configurazione', 'Supporto tecnico', 'Smartphone e Tablet', 'Configurazione email', 'Configurazione email su iPhone', '<h5>Per aggiungere il tuo account di posta Alice sul dispositivo, tocca dal menu l''icona Impostazioni:<br><br>\r\n\r\nNelle Impostazioni:<br><br>\r\n\r\nscegli la voce Posta, contatti, calendari<br>\r\nquindi Aggiungi account...<br>\r\ndall''elenco dei provider vai su Altro:<br><br>\r\n\r\n\r\ntocca l''opzione Aggiungi account Mail<br>\r\ncompila i campi con i tuoi dati della casella di posta Alice:<br>\r\nNome: inserisci un nome a tua scelta;<br>\r\nIndirizzo: il tuo indirizzo completo del dominio @alice.it;<br>\r\nPassword: digita la tua password di posta;<br>\r\nDescrizione: inserisci un nome per specificare questo account (Alice, Casa, Ufficio, ...).<br>\r\ntocca infine il tasto Avanti:<br><br>\r\n\r\nIl dispositivo nei passaggi successivi verifica automaticamente l''esistenza dell''account e il corretto funzionamento dei server di posta in entrata ed in uscita:<br><br>\r\n\r\nSe visualizzi il seguente avviso al termine della verifica ; tocca il tasto Si per completare la configurazione:<br><br>\r\n\r\nPer accedere alla casella di posta tocca l''icona Mail dal menu principale e seleziona il tuo account.<br><br>\r\n\r\n\r\nN.B. Il dispositivo Configura in automatico la tua casella alice secondo il protocollo IMAPche permette di mantenere sincronizzata la tua mail con il server di posta; in questo modo anche l''eliminazione dei tuoi messaggi dal server avviene solo quando effettui la cancellazione da iPhone. Ti consigliamo di mantenere questa impostazione.<br><br>\r\n\r\nSe hai necessita'' di configurare la mail su protocollo POP3 clicca sotto su ''Configurazione POP3''<br><br>\r\n\r\nSe trovi comunque difficolta'' nella configurazione, ti informiamo che e'' disponibile il nostro servizio di assistenza a pagamento SOS PC: il personale tecnico concordera'' un intervento personalizzato per configurare in maniera ottimale il tuo dispositivo.</h5>', 1),
(4, 'configurazione', 'Supporto tecnico', 'Smartphone e Tablet', 'Configurazione email', 'Configurazione email su iPad', '<h5>Per aggiungere il tuo account di posta Alice sul dispositivo, tocca dal menu l''icona Impostazioni:<br><br>\r\n\r\nNelle Impostazioni:<br><br>\r\n\r\nscegli la voce Posta, contatti, calendari<br>\r\nquindi Aggiungi account...<br>\r\ndall''elenco dei provider vai su Altro:<br><br>\r\n\r\n\r\ntocca l''opzione Aggiungi account Mail<br>\r\ncompila i campi con i tuoi dati della casella di posta Alice:<br>\r\nNome: inserisci un nome a tua scelta;<br>\r\nIndirizzo: il tuo indirizzo completo del dominio @alice.it;<br>\r\nPassword: digita la tua password di posta;<br>\r\nDescrizione: inserisci un nome per specificare questo account (Alice, Casa, Ufficio, ...).<br>\r\ntocca infine il tasto Avanti:<br><br>\r\n\r\nIl dispositivo nei passaggi successivi verifica automaticamente l''esistenza dell''account e il corretto funzionamento dei server di posta in entrata ed in uscita:<br><br>\r\n\r\nSe visualizzi il seguente avviso al termine della verifica ; tocca il tasto Si per completare la configurazione:<br><br>\r\n\r\nPer accedere alla casella di posta tocca l''icona Mail dal menu principale e seleziona il tuo account.<br><br>\r\n\r\n\r\nN.B. Il dispositivo Configura in automatico la tua casella alice secondo il protocollo IMAPche permette di mantenere sincronizzata la tua mail con il server di posta; in questo modo anche l''eliminazione dei tuoi messaggi dal server avviene solo quando effettui la cancellazione da iPhone. Ti consigliamo di mantenere questa impostazione.<br><br>\r\n\r\nSe hai necessita'' di configurare la mail su protocollo POP3 clicca sotto su ''Configurazione POP3''<br><br>\r\n\r\nSe trovi comunque difficolta'' nella configurazione, ti informiamo che e'' disponibile il nostro servizio di assistenza a pagamento SOS PC: il personale tecnico concordera'' un intervento personalizzato per configurare in maniera ottimale il tuo dispositivo.</h5>', 0),
(5, 'configurazione', 'Supporto tecnico', 'Smartphone e Tablet', 'Configurazione email', 'Configurazione email su Android', '<h5>Per aggiungere il tuo account di posta Alice sul dispositivo, tocca dal menu l''icona Impostazioni:<br><br>\r\n\r\nNelle Impostazioni:<br><br>\r\n\r\nscegli la voce Posta, contatti, calendari<br>\r\nquindi Aggiungi account...<br>\r\ndall''elenco dei provider vai su Altro:<br><br>\r\n\r\n\r\ntocca l''opzione Aggiungi account Mail<br>\r\ncompila i campi con i tuoi dati della casella di posta Alice:<br>\r\nNome: inserisci un nome a tua scelta;<br>\r\nIndirizzo: il tuo indirizzo completo del dominio @alice.it;<br>\r\nPassword: digita la tua password di posta;<br>\r\nDescrizione: inserisci un nome per specificare questo account (Alice, Casa, Ufficio, ...).<br>\r\ntocca infine il tasto Avanti:<br><br>\r\n\r\nIl dispositivo nei passaggi successivi verifica automaticamente l''esistenza dell''account e il corretto funzionamento dei server di posta in entrata ed in uscita:<br><br>\r\n\r\nSe visualizzi il seguente avviso al termine della verifica ; tocca il tasto Si per completare la configurazione:<br><br>\r\n\r\nPer accedere alla casella di posta tocca l''icona Mail dal menu principale e seleziona il tuo account.<br><br>\r\n\r\n\r\nN.B. Il dispositivo Configura in automatico la tua casella alice secondo il protocollo IMAPche permette di mantenere sincronizzata la tua mail con il server di posta; in questo modo anche l''eliminazione dei tuoi messaggi dal server avviene solo quando effettui la cancellazione da iPhone. Ti consigliamo di mantenere questa impostazione.<br><br>\r\n\r\nSe hai necessita'' di configurare la mail su protocollo POP3 clicca sotto su ''Configurazione POP3''<br><br>\r\n\r\nSe trovi comunque difficolta'' nella configurazione, ti informiamo che e'' disponibile il nostro servizio di assistenza a pagamento SOS PC: il personale tecnico concordera'' un intervento personalizzato per configurare in maniera ottimale il tuo dispositivo.</h5>', 0),
(6, 'configurazione', 'Supporto tecnico', 'Smartphone e Tablet', 'Configurazione email', 'Configurazione email su WP', '<h5>Per aggiungere il tuo account di posta Alice sul dispositivo, tocca dal menu l''icona Impostazioni:<br><br>\r\n\r\nNelle Impostazioni:<br><br>\r\n\r\nscegli la voce Posta, contatti, calendari<br>\r\nquindi Aggiungi account...<br>\r\ndall''elenco dei provider vai su Altro:<br><br>\r\n\r\n\r\ntocca l''opzione Aggiungi account Mail<br>\r\ncompila i campi con i tuoi dati della casella di posta Alice:<br>\r\nNome: inserisci un nome a tua scelta;<br>\r\nIndirizzo: il tuo indirizzo completo del dominio @alice.it;<br>\r\nPassword: digita la tua password di posta;<br>\r\nDescrizione: inserisci un nome per specificare questo account (Alice, Casa, Ufficio, ...).<br>\r\ntocca infine il tasto Avanti:<br><br>\r\n\r\nIl dispositivo nei passaggi successivi verifica automaticamente l''esistenza dell''account e il corretto funzionamento dei server di posta in entrata ed in uscita:<br><br>\r\n\r\nSe visualizzi il seguente avviso al termine della verifica ; tocca il tasto Si per completare la configurazione:<br><br>\r\n\r\nPer accedere alla casella di posta tocca l''icona Mail dal menu principale e seleziona il tuo account.<br><br>\r\n\r\n\r\nN.B. Il dispositivo Configura in automatico la tua casella alice secondo il protocollo IMAPche permette di mantenere sincronizzata la tua mail con il server di posta; in questo modo anche l''eliminazione dei tuoi messaggi dal server avviene solo quando effettui la cancellazione da iPhone. Ti consigliamo di mantenere questa impostazione.<br><br>\r\n\r\nSe hai necessita'' di configurare la mail su protocollo POP3 clicca sotto su ''Configurazione POP3''<br><br>\r\n\r\nSe trovi comunque difficolta'' nella configurazione, ti informiamo che e'' disponibile il nostro servizio di assistenza a pagamento SOS PC: il personale tecnico concordera'' un intervento personalizzato per configurare in maniera ottimale il tuo dispositivo.</h5>', 0),
(10, 'configurazione', 'Supporto tecnico', 'Decoder e TV', 'TIM vision', 'Decoder TIM VIsion', '<h5>\r\nPer vedere subito tutti i canali TIMvision guarda il video per collegare il decoder<br><br>\r\n\r\n<a>https://www.youtube.com/watch?list=PLEHvG0moB2apF81ljbvhmLs2g0v57BkWt&v=l_08EJ6jzYk<a> <h5>\r\n\r\n', 1),
(11, 'configurazione', 'Supporto tecnico', 'Decoder e TV', 'TIM SKY', 'Funzionalita'' TIM SKY', 'Il servizio SKY e'' disponibile per tutti i clienti con linea Fibra e per i clienti con linea ADSL 20 Mega *<br><br>\r\n\r\nPer il corretto funzionamento e per garantire la visione ottimale dei contenuti SKY ciascun clilente ricevera'' in dotazione il nuovo decoder MY SKY HD ed il modem Fibra per i clienti TIM Sky .   <br><br>\r\n\r\nE'' possibile collegare i dispositivi tramite il con cavo ethernet oppure tramite la rete Wi-Fi a 5 Ghz solo ed unicamnete tramite il dispositivo SKY Link .<br><br>  \r\n\r\nPer collegare e installare il decoder, configurare  il servizio TIM Sky e avere indicazioni sui messaggi di errore, consulta le guide di dettaglio oppure guarda il video di seguito per sapere come fare:<br><br>\r\n<a>https://youtu.be/s6OtU6b51Hw</a></h5>', 1),
(12, 'configurazione', 'Supporto tecnico', 'Decoder e TV', 'TIM SKY', 'Installazione My Sky HD decoder', '<h5>Collega il decoder My Sky HD tramite il cavo ethernet o tramite la rete Wi-Fi se disponi del dispositivo Sky Link e segui i passi descritti nella guida prima installazione.<br><br>\r\n\r\nScegli di seguito la guida al collegamento o, se hai gia'' collegato il decoder, consulta la guida di installazione per sapere come procedere e vedere tutti i canali Sky.</h5>', 0),
(15, 'configurazione', 'Supporto tecnico', 'Decoder e TV', 'Premium Online', 'Errori comuni', '<h3>Username o Password errate</h3>\r\n<h5>Se durante la visione dei contenuti sullo schermo della TV, dal PC o dal tuo smartphone/tablet , visualizzi i messaggi:<br><br>\r\n\r\n\r\nUsername e/o password errati - (A01-3036) (A72-3036)<br>\r\nUsername e/o password errati - (A01-3161)<br>\r\nE'' possibile che la username o la password siano state inserite piu'' di 5 volte in maniera errata. <br>\r\nVerifica che l''inserimento delle lettere maiuscole e minuscole sia stato rispettato e di aver copiato, senza inserire alcun spazio vuoto, le credenziali di accesso dalla email ricevuta dopo la sottoscrizione del servizio.\r\n<br><br>\r\nSe continui a riscontrare il problema, accedi alla pagina XXXX, clicca sul link Recupera Password ed inserisci l''email usata per la sottoscrizione di Premium Online. La nuova password ti verra'' automaticamente inviata. </h5>', 0),
(17, 'configurazione', 'Supporto tecnico', 'Navigazione internet', 'Impostazioni navigatore', 'Configurazione DNS', '<h3>Configurazione su Windows 7</h3>\r\n\r\n<h5>Windows 7 e'' predisposto, per la connessione Internet, per l''acquisizione automatica dell''indirizzo IP da router.<br><br>\r\n\r\nSe hai sottoscritto un abbonamento ADSL con profilo flat e se sul tuo PC e'' presente una scheda di rete LAN, per navigare e'' sufficiente collegare il cavo Ethernet del modem Telecom Italia all''ingresso di rete LAN del PC.<br><br>\r\n\r\nPer verificare le impostazioni della scheda di rete, clicca sul menu Start e poi su Pannello di controllo:<br><br>\r\n\r\n\r\n\r\nNella finestra del Pannello di controllo clicca su Rete e Internet:<br><br>\r\n\r\n\r\n\r\nAll''interno di Centro connessioni di rete e condivisione, clicca sulla voce a sinistra Modifica impostazioni scheda:<br><br>\r\n\r\n\r\n\r\nSu Connessione alla rete locale (LAN), clicca con il tasto destro del mouse e quindi seleziona Proprieta'':<br><br>\r\n\r\n\r\n\r\nSeleziona Protocollo Internet versione 4 (TCP/IPv4) e clicca sul pulsante Proprieta'':<br><br>\r\n\r\n\r\n\r\nIl protocollo TCP/IPv4 deve essere configurato per ottenere automaticamente un indirizzo IP e DNS, come illustrato nell''immagine seguente:<br><br>\r\n\r\n\r\n\r\nPer confermare le impostazioni, premi il tasto OK<br><br>\r\n\r\nN.B. Le impostazioni suggerite sono valide se il tuo PC, per connettersi ad Internet, e'' direttamente collegato ad un router.<br>\r\nSe hai necessita'' di configurare la scheda di rete di un PC all''interno di una rete LAN domestica o aziendale, e'' necessario contattare un tecnico o l''amministratore di rete.</h5>', 1),
(19, 'configurazione', 'Supporto tecnico', 'Navigazione internet', 'Problemi di Navigazione', 'La Connessione e'' lenta', '<h5>Prima di procedere con le verifiche, controlla sul tuo computer che non siano attivi programmi che occupano la banda Internet disponibile (ad es. lo scambio diretto di file tra utenti Internet, peer-to-peer, etc.), in tal caso disattivali e prova nuovamente a navigare.<br><br>\r\n\r\nSe il problema si presenta soltanto su alcuni siti, questo puo'' dipendere dal gestore del sito stesso o da problemi temporanei sulla rete Internet.<br><br>\r\n\r\nSe ancora navighi lentamente dopo aver effettuato i controlli e tutte le Verifiche proposte, puoi aprire una segnalazione o contattare direttamente l''Assistenza tecnica tramite i pulsanti presenti al termine del percorso.</h5>', 1),
(21, 'contenuti', 'Smart Life', 'TIM Games', 'Scopri TIM Games', 'Cos''e'' TIM Games', '<h5>TIMgames e'''' un servizio TIM dedicato al gaming che consente a tutti i clienti di scaricare su tablet e smartphone i migliori giochi on demand e in abbonamento per il mondo mobile.<br>\r\nCon TIMgames avrai a disposizione una library di oltre 1500 giochi, aggiornata ogni settimana con nuovi titoli e giochi in offerta presenti nell''area promozioni dello store.<br>\r\nTIMgames e'' accessibile sia da App (scaricabile da Google Play) che da browser su www.timgames.it L''utente puo'' scegliere la modalita'' di acquisto preferita tra on demand e abbonamento.<br><br>\r\n\r\nIn particolare:<br><br>\r\n\r\nOn demand: a partire da 0,49euro, acquistando e scaricando un gioco sul proprio telefonino;<br><br>\r\n\r\nIn abbonamento: con I Love Games Promo, a soli 2 euro a settimana si possono scaricare senza limiti tutti i giochi presenti su TIMgames. Il primo mese e'' in promozione a solo 1 euro a settimana.</h5>', 1),
(22, 'contenuti', 'Smart Life', 'TIM Games', 'Scopri TIM Games', 'Tutti i modi per abbonarsi', '<h5>Con TIMgames hai la possibilita'' di scegliere tutti i giochi che vuoi per il tuo telefonino in due semplici modalita'':<br><br>\r\n\r\nOn demand: basta accedere al sito mobile www.timgames.it oppure dall''App TIMgames e scegliere tutti i giochi presenti. Il prezzo e'' indicato accanto ad ogni titolo. Inoltre, all''interno della sezione promozioni, troverai molti giochi da provare gratuitamente prima di effettuare l''acquisto;<br>\r\nAbbonamento: per attivare I Love Games Promo, a soli 2 euro a settimana in promo a meta'' prezzo per il primo mese, puoi andare in qualsiasi negozio TIM, chiamare il 119, il 409167 oppure tramite il sito tim.it<br>\r\nIn entrambi i casi, accedendo alla sezione MyTIMgames, potrai visualizzare tutti i giochi scaricati e gestire gli abbonamenti sottoscritti.\r\n</h5>', 0),
(23, 'contenuti', 'Smart Life', 'TIM Music', 'Scopri TIM Music', 'Cos''e'' TIM Music', '<h5>TIMmusic e'' la piattaforma di musica digitale di Telecomitalia dedicata a tutti i clienti che hanno uno smartphone/tablet TIM o una linea ADSL o Fibra  residenziale Telecom Italia o una chiavetta Internet TIM.<br><br>\r\n\r\nCon TIMmusic puoi ascoltare milioni di brani in streaming senza limiti di tempo sul tuo smartphone e tablet o sul PC (clienti ADSL e Fibra Residenziale Telecom Italia o con chiavetta Internet TIM). Puoi  creare tue playlist personali o ascoltare quelle suggerite da dj e artisti famosi e condividere tutto sui principali social network. Il catalogo e'' sempre aggiornato con tutte le ultime uscite discografiche, spesso anche in anteprima esclusiva. E , se sei su mobile, non consumi GB perchè il traffico dati per l''ascolto di musica e'' incluso nel costo dell''abbonamento.</h5>', 1),
(24, 'contenuti', 'Smart Life', 'TIM Music', 'Scopri TIM Music', 'Tutti i modi per acquistare', '<h5>Se sei un cliente TIM puoi attivare l''abbonamento per Smartphone e Tablet direttamente nella sezione "Abbonamento" della App. Per iOS occorre accedere dallo smartphone o  tablet a timmusic.it.<br><br>\r\n\r\nSi puo'' attivare TIMmusic anche presso i negozi TIM, chiamando il 40916 (seguendo la voce guida) o da tim.it (anche per chiavetta TIM).<br><br>\r\n\r\nSe sei un cliente con una linea ADSL o Fibra  residenziale Telecom Italia puoi attivare l''Abbonamento TIMmusic per fruirne su PC, da  sito timmusic.it,  dal sito tim.it oppure chiamando il 187.</h5>', 0),
(25, 'contenuti', 'Smart Life', 'TIM Reading', 'Scopri TIM Reading', 'Cos''e'' TIM Reading', '<h5>TIMreading e'' lo Store di TIM che permette di acquistare e leggere eBook, quotidiani e Magazine su PC, Tablet e Smartphone.<br><br>\r\n\r\nI contenuti disponibili sullo store sono:<br><br>\r\n\r\n11 quotidiani nazionali e sportivi, completi di allegati ed edizioni locali, disponibili in abbonamento settimanale o mensile sul proprio PC, Tablet o Smartphone, per seguire l''informazione dalle prime ore del mattino.<br><br>\r\n\r\noltre 50 Magazine in copia singola o in abbonamento, per scoprire le nuove tendenze e nuove mete, seguire i gossip e l''attualita''.<br><br>\r\n\r\noltre 75.000 eBook tra best seller, gialli, romanzi rosa, classici e tanto altro, per passare il tempo leggendo un buon libro.<br><br><br>\r\n\r\n \r\n\r\nPuoi attivare diverse offerte per scoprire il servizio TIMreading:<br><br>\r\n\r\nAbbonamenti a quotidiani e abbonamenti o copie singole di magazine dal sito TIMreading.<br><br>\r\n\r\nPresso i Negozi TIM o sul sito TIM l''abbonamento ad un quotidiano a partire da 15,99 euro/mese, con i primi 3 mesi gratis o l''abbonamento "I Love Mags" per scegliere ogni mese le riviste che preferisci.<br><br>\r\n\r\nPresso i Negozi TIM l''abbonamento ad una rivista a partire da 10,99 euro/mese e hai un secondo abbonamento a scelta in regalo<br><br>\r\n\r\nOgni eBook ha il proprio prezzo ed ogni giorno su TIMreading almeno un libro e'' offerto con oltre il 60% di sconto.</h5>', 1),
(26, 'contenuti', 'Smart Life', 'TIM Reading', 'Scopri TIM Reading', 'Tutti i modi per acquistare', '<h5>e sei un cliente TIM puoi attivare l''abbonamento per Smartphone e Tablet direttamente nella sezione "Abbonamento" della App. Per iOS occorre accedere dallo smartphone o  tablet a timreading.it.<br><br>\r\n\r\nSi puo'' attivare TIMreading anche presso i negozi TIM, chiamando il 40916 (seguendo la voce guida) o da tim.it (anche per chiavetta TIM).<br><br>\r\n\r\nSe sei un cliente con una linea ADSL o Fibra  residenziale Telecom Italia puoi attivare l''Abbonamento TIMmusic per fruirne su PC, da  sito timreading.it,  dal sito tim.it oppure chiamando il 187.</h5>', 0),
(27, 'contenuti', 'Smart Life', 'TIM Vision', 'Scopri TIM Vision', 'Scopri TIM Vision', '<h5>TIMvision e'' la nuova risposta alle esigenze di intrattenimento per tutta la famiglia. E''la TV on demand di TIM che tramite una connessione ADSL Illimitata o Fibra ti permette di godere di migliaia di titoli.<br><br>\r\n\r\nI clienti TIMvision possono accedere a:<br><br>\r\n\r\nTIMvision TV<br>\r\nVideostore<br>\r\nFree<br>\r\nReplay TV<br>\r\nL''abbonamento TIMvision ti permette di guardare tutti i contenuti su PC, Smart TV o TV con Decoder, tablet e smartphone senza consumare Giga, quando e dove vuoi.</h5>', 1),
(28, 'contenuti', 'Smart Life', 'TIM Vision', 'Scopri TIM Vision', 'Tutti i modi per abbonarsi', '<h5>L''abbonamento a TIMvision puo'' essere fatto mediante diverse modalita''.<br><br><br>\r\n\r\n \r\n\r\nSe sei cliente TIM, puoi procedere direttamente online dalla sezione OFFERTE o se preferisci recandoti presso un Negozio TIM.<br><br><br>\r\n\r\n \r\n\r\nPuoi richiedere l''abbonamento a TIMvision anche contattando il Servizio Clienti 187 o il 119.<br><br><br>\r\n\r\n \r\n\r\nSe possiedi una Smart TV compatibile (Samsung o Lg) potrai abbonarti, una volta scaricata l''app TIMvision, dalla sezione "TIMvision TV".<br><br>\r\n\r\n \r\n\r\nPuoi scegliere,  come metodo di pagamento, l''addebito in fattura su linea fissa TIM o la tua carta di credito Visa, Mastercard o American Express.<br><br>\r\n\r\nPer l''addebito in fattura, su linea fissa TIM, devi essere un cliente con ADSL/FIBRA  di TIM e devi effettuare l''acquisto collegandoti dalla linea di casa, sia tramite collegamento ethernet che tramite Wi-Fi. In questo caso, per completare l''acquisto dell''abbonamento TIMvision TV o anche di un titolo del Videostore, ti verra'' richiesto di impostare un PIN per garantirti un acquisto in totale sicurezza.<br><br>\r\n\r\nSe sei un cliente con linea fissa di altro operatore potrai abbonarti a TIMvision pagando con la carta di credito.<br><br><br>\r\n \r\n\r\n\r\nUn altro modo semplice per abbonarsi e'' da app su Tablet/Smartphone. Scarica l''app TIMvision dall''App Store ed entra nella sezione "TIMvision TV". Puoi scegliere come metodo di pagamento il credito residuo o la tua carta di credito Visa, Mastercard o American Express.</h5>', 0),
(29, 'costi', 'Controllo costi e Pagamento', 'Fisso', 'Fatture e Pagamenti', 'Come leggere la fattura della linea fissa', '<h5>La fattura della linea fissa e'' semplice e facile da leggere perche'' disegnata prendendo spunto dai suggerimenti dei clienti.<br> La veste grafica, moderna e raffinata, utilizza un linguaggio sempre piu'' chiaro per l''esposizione delle voci di spesa, facilitando la lettura di tutte le informazioni di cui hai bisogno e garantendo maggiore trasparenza nei contenuti e negli importi.</h5>', 0),
(30, 'costi', 'Controllo costi e Pagamento', 'Fisso', 'Fatture e Pagamenti', 'Come pagare la fattura della linea fissa', '<h5>Seguono i diversi modi in cui e'' possibile effettuare il pagamento:<br><br>\r\nOnline nella sezione MyTIM Fisso<br><br>\r\nApp MyTIM Fisso da smartphone/tablet<br><br>\r\nServizio Clienti linea fissa 187(e'' necessario comunicare il codice Iban del conto corrente) <br><br>\r\nDirettamente al tuo istituto bancario o postale</h5>', 1),
(31, 'costi', 'Controllo costi e Pagamento', 'Mobile', 'Ricaricabile', 'Come pagare la fattura della linea mobile', '<h5>Il credito residuo disponibile, le offerte e lo stato dei bonus attivi sulla tua linea ricaricabile, sono consultabili attraverso le seguenti modalita'':<br><br>\r\n\r\nDirettamente dal tuo Smartphone, accedendo all''app MyTIM Mobile, attualmente disponibile in download gratuito nelle versioni per iPhone e per smartphone con sistema operativo Android.\r\n\r\n\r\nDirettamente online sul sito tim.it nella sezione MyTIM Mobile riservata ai nostri clienti che ti permette di verificare il credito residuo, le quantita'' di minuti, SMS, GB ancora disponibili, i bonus in euro  eventualmente presenti ed effettuare variazioni sulla tua linea telefonica.<br>\r\nChiamando il numero gratuito 40916, per il credito residuo. Inoltre digitando il tasto 1 puoi conoscere le offerte attive, la quantita'' di minuti, SMS, GB ancora disponibili e i bonus in euro eventualmente presenti.<br>\r\nAttraverso il servizio gratuito 119sms; inviando un sms al 119 "a testo libero"(ad esempio "qual e'' il mio credito residuo") il servizio ti rispondera'' con un sms con le informazioni richieste.<br>\r\nAttraverso l''attivazione del servizio gratuito "TIM Ti Avvisa - info sms" che ti permette di conoscere il costo dell''ultima chiamata nazionale effettuata e il credito residuo aggiornato in tempo reale grazie alla ricezione di un sms direttamente sul tuo telefonino oppure con il servizio "TIM Ti Avvisa - offerte" puoi essere informato con un sms gratuito quando il consumo delle tue offerte attive raggiunge la percentuale da te scelta.</h5>', 0),
(32, 'gestione', 'Gestione Linea e Servizi', 'Fisso', 'Gestione della linea', 'Attivazione Linea di casa', '<h5>Richiedere l''attivazione di una linea telefonica di casa e'' molto semplice, puoi:<br><br>\r\n\r\nrichiederla online<br>\r\nchiamare il Servizio Clienti linea fissa 187<br>\r\nrecarti presso un Negozio TIM<br><br>\r\nVerifica la modalita'' di attivazione consultando on line le varie offerte. disponibili.<br><br>\r\n\r\nI dati necessari sono:<br><br>\r\n\r\nnome e cognome<br>\r\ncodice fiscale<br>\r\nindirizzo dell''abitazione per cui richiedi l''installazione della linea<br>\r\nun recapito telefonico di cellulare<br>\r\nindirizzo email (facoltativo).<br>\r\nIl nostro personale tecnico ti contattera'' quanto prima per concordare l''appuntamento per l''installazione dell''impianto telefonico.</h5>', 0),
(33, 'gestione', 'Gestione Linea e Servizi', 'Fisso', 'Gestione della linea', 'Variazione Abbonamento', '<h5>Se hai cessato la tua attivita'' professionale, puoi richiedere la variazione del tuo contratto di abbonamento telefonico.<br>\r\nPer richiedere la variazione chiama il Servizio Clienti 191.\r\n<br><br>\r\nCon la richiesta della trasformazione del contratto dalla categoria Affari ("A") alla categoria Residenziale ("B") il costo del tuo abbonamento mensile passera'' da:<br><br>\r\n\r\n22,50 euro (IVA esclusa) a 17,54 euro (IVA al 22% inclusa), in caso di linea telefonica di base<br>\r\n31,00 euro (IVA esclusa) a 20,17 euro (IVA al 22% inclusa), in caso di linea ISDN.</h5>', 1),
(36, 'gestione', 'Gestione Linea e Servizi', 'Mobile', 'Attivare e disattivare servizi a contenuto (CSP) e servizi telefonici', 'LoSai e ChiamaOra di TIM', '<h5>LoSai di TIM, ti informa sulle chiamate ricevute mentre hai il telefonino spento, non raggiungibile, quando sei occupato in un''altra conversazione e negli altri casi in cui non è stato possibile contattarti.<br>\r\nQuando torni disponibile riceverai un SMS di notifica, il cui mittente e'' il numero di chi ti ha cercato e nel testo e'' indicata la data e l''ora della chiamata ricevuta.<br>\r\nSe il numero di chi ti ha cercato e'' salvato nella tua rubrica, vedrai direttamente il suo nome come mittente e potrai richiamare, o inviare un SMS, direttamente dopo aver letto il messaggio di notifica.<br>\r\nCon LoSai di TIM ricevi un SMS per ogni chiamata persa, sia quando sei in Italia sia quando ti trovi all''Estero senza costi aggiuntivi rispetto al costo dell''abbonamento.<br><br><br>\r\n \r\n\r\nChiamaOra di TIM, ti permette di sapere sempre quand''è il momento giusto per richiamare chi stai cercando.<br>\r\nQuando la persona che stai chiamando al momento non puo'' rispondere, perche'' ha il telefonino spento, fuori copertura o e'' occupata in un''altra conversazione, il servizio ChiamaOra di TIM ti consente di ricevere un SMS di avviso, oppure di prenotare la richiamata automatica, non appena la persona cercata torna contattabile.<br>\r\nL''utilizzo del ChiamaOra di TIM è semplicissimo!<br><br>\r\nQuando chiami un tuo amico ed ascolti la fonia di cortesia del servizio puoi decidere di:<br><br>\r\nchiudere subito la chiamata e ricevere un SMS di avviso quando il tuo amico tornera'' contattabile (nel testo dell''SMS sarà indicata l''ora in cui e'' tornato raggiungibile).<br>\r\nse invece vuoi prenotare la richiamata automatica, attendendo in linea, quando la persona chiamata tornera'' raggiungibile il tuo telefonino squillera'' e, rispondendo, ChiamaOra di TIM richiamera'' per te la persona cercata.<br>\r\nLa richiamata sarà tariffata in base al tuo piano tariffario. Se invece hai attivato una delle opzioni tariffarie di TIM (voce, SMS, Internet), le richiamate sono tariffate secondo le condizioni previste da tali offerte.</h5>', 0),
(35, 'gestione', 'Gestione Linea e Servizi', 'Mobile', 'Gestione della tua SIM', 'Passaggio da abbonamento a ricaricabile', '<h5>Per passare la tua utenza TIM da abbonamento a servizio ricaricabile puoi compilare il modulo di "Richiesta di migrazione da abbonamento a ricaricabile". Il modulo e'' disponibile in formato pdf nella sezione Moduli e puo'' essere scaricato direttamente dalla sottosezione "clienti con abbonamento".<br>\r\nPotrai inviare il modulo compilato con la richiesta di cessazione del contratto di abbonamento e la specificata volonta'' di passare verso servizio ricaricabile (indicando il profilo e l''eventuale opzione) e la modalita'' di rimborso ACI (assegno/accredito su linea ricaricabile), al numero di fax dedicato 800600119.<br><br>\r\n\r\nPuoi effettuare il passaggio scrivendoci o in alternativa presso un qualsiasi Negozio TIM.</h5>', 0);

-- --------------------------------------------------------

--
-- Struttura della tabella `ass_for_devices`
--

CREATE TABLE IF NOT EXISTS `ass_for_devices` (
  `id_ass` int(5) NOT NULL,
  `id_dev` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_ass`,`id_dev`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `ass_for_devices`
--

INSERT INTO `ass_for_devices` (`id_ass`, `id_dev`) VALUES
(3, 1),
(3, 3),
(4, 3),
(4, 4),
(5, 4),
(5, 5),
(6, 5),
(6, 6),
(10, 1000),
(10, 2000),
(11, 1000),
(11, 2000),
(12, 1000),
(12, 2000),
(15, 1000),
(15, 2000),
(17, 1),
(17, 20),
(17, 3000),
(19, 3),
(19, 50),
(19, 5000),
(21, 2),
(21, 4),
(22, 1),
(22, 30),
(22, 60),
(23, 4),
(23, 40),
(24, 6),
(24, 50),
(25, 2),
(25, 30),
(26, 5),
(26, 60),
(27, 1000),
(27, 2000),
(28, 1000),
(28, 2000),
(29, 4000),
(29, 5000),
(30, 4000),
(30, 5000),
(31, 5),
(31, 30),
(32, 4000),
(32, 5000),
(33, 4000),
(33, 5000);

-- --------------------------------------------------------

--
-- Struttura della tabella `modem`
--

CREATE TABLE IF NOT EXISTS `modem` (
  `id` int(11) NOT NULL,
  `nome` varchar(30) NOT NULL,
  `colore` varchar(30) NOT NULL,
  `caratteristiche` varchar(200) NOT NULL,
  `specifiche` longtext NOT NULL,
  `prezzo` double NOT NULL,
  `immagine_front` varchar(40) NOT NULL,
  `immagine_back` varchar(40) NOT NULL,
  `immagine_side` varchar(40) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `modem`
--

INSERT INTO `modem` (`id`, `nome`, `colore`, `caratteristiche`, `specifiche`, `prezzo`, `immagine_front`, `immagine_back`, `immagine_side`) VALUES
(1, 'Repeater Wi-Fi ZyXEL AC750', 'white', 'Funzionamento simultaneo a 2.4 e 5 GHz<br>\r\n\r\nVelocità di trasmissione fino a 750 Mbps<br>\r\n\r\nCompatibilità Wi-Fi b/g/n a 2.4 GHz e Wi-Fi n/ac a 5 GHz<br>\r\n\r\nAssociazione al modem in modalita'' WPS\r\n', '\r\nStandard Wi-Fi<br>\r\n\r\n\r\n802.11 a / b / g / n / ac <br><br>\r\n\r\n\r\n\r\nVelocita'' Wi-Fi<br>\r\n\r\n\r\n300 Mbps * (2,4 GHz), 450 Mbps * (5 GHz) Ricezione: 300 Mbps * (2,4 GHz), 450 Mbps * (5 GHz) <br><br>\r\n\r\n\r\n\r\nSicurezza Wi-Fi<br>\r\n\r\n\r\n64/128 bit WEP, WPA / WPA2, WPA-PSK / WPA2-PSK <br><br>\r\n\r\n\r\n\r\nCaratteristiche operative<br>\r\n\r\n\r\nModalita'' Ripetitore, Modalita'' AP, Wi-Fi Protected Setup (WPS), Wi-Fi Multimedia (WMM),Selezione automatica dei canali, Programmazione senza fili, Gestione di potenza di uscita senza fili,Filtraggio degli indirizzi MAC, Modalita'' di impostazione di copertura. <br><br>\r\n\r\n\r\nSpecifiche hardware<br>\r\n\r\n\r\nLAN: 10/100 Mbps One Ethernet RJ-45 porta con auto MDI / MDIX supporto <br><br>\r\n\r\n\r\n\r\nDimensioni<br>\r\n\r\n\r\n(LxPxA): 46,5 x 62,3 x 90,9 mm <br><br>\r\n\r\n\r\n\r\nPeso<br>\r\n\r\n\r\n98 g <br><br>\r\n\r\n\r\n\r\nAmbiente operativo<br>\r\n\r\n\r\nTemperatura: 0 ° C a 40 ° C (32 ° F a 104 ° F) Umidità: 10% a 90% (senza condensa) <br><br>\r\n\r\n\r\n\r\nContenuto della confezione<br><br>\r\n\r\n\r\n\r\n\r\nWireless Range Extender,<br>\r\n\r\nCavo Ethernet,<br>\r\n\r\nGuida rapida,<br>\r\n\r\nCertificato di garanzia,<br>\r\n\r\nCD di supporto\r\n', 49.99, 'modem1-front.jpg', '', ''),
(2, 'TIM Modem Wi-Fi Car Pack 4G ', 'white', 'Modem WI-FI CarPack4G<br>\r\nCodice PIN promozionale per 6 mesi di Servizi Assistenza ACI Global<br>\r\n\r\nAlimentatore da rete<br>\r\n\r\nAlimentatore da auto<br>\r\n\r\n\r\n', '\r\nTecnologia<br>\r\n\r\n\r\n\r\n\r\n4G - DC-HSDPA - HSPA+ - HSDPA - HSUPA - EDGE/GPRS<br><br>\r\n\r\n\r\n\r\n\r\nFrequenze<br>\r\n\r\n\r\n\r\n\r\n4G: 800/1800/2600 Mhz, download fino a 100Mbps, upload fino a 40Mbps<br>\r\nDC-HSDPA: 900/2100 Mhz, download fino a 42.2Mbps<br>\r\nHSPA+: 900/2100 Mhz, download fino a 21.1 Mbps<br>\r\nHSDPA: 900/2100 Mhz, download fino a 14.4 Mbps<br>\r\nHSUPA: 900/2100 Mhz, upload fino a 5.76 Mbps<br>\r\nEDGE/GPRS: 850/900/1800/1900 Mhz<br><br>\r\n\r\n\r\n\r\n\r\nContenuto della Confezione<br>\r\n\r\n\r\n\r\n\r\nModem 4G Wi-Fi - TIM Card con 1 euro di traffico prepagato incluso - Alimentatore da rete - Alimentatore da auto - Cavetto USB - Guida rapida – Card con PIN ACI Global per usufruire della Promozione<br><br>\r\n\r\n\r\n\r\n\r\nRequisiti di Sistema<br>\r\n\r\n\r\nLa compatibilita'' e'' totale per tutti i dispositivi certificati Wi-Fi (802.11b/g/n). \r\n', 99.99, 'modem2-front.jpg', '', ''),
(3, 'Wi-Fi Bridge Technicolor', 'black', 'Design verticale compatto<br>\r\nWi-Fi AC 4x4 ad altissime prestazioni<br>\r\nAssociazione al modem in modalità WPS<br>\r\nDue porte Gigabit Ethernet<br>\r\nLed di stato<br>\r\n', '\r\nTecnologia<br>\r\n\r\n\r\n\r\n\r\nWi-Fi IEEE 802.11ac 5 GHz 4x4<br><br>\r\n\r\n\r\n\r\n\r\nInterfacce<br>\r\n\r\n\r\n\r\n\r\n2 Porte Ethernet<br><br>\r\n\r\n\r\n\r\n\r\nContenuto della confezione<br>\r\n\r\n\r\n\r\n\r\nMultimedia Connect; Alimentatore; Cavo Ethernet; Guida rapida; Garanzia di conformita''; Foglio di sicurezza<br><br>\r\n', 99.99, 'modem3-front.jpg', '', ''),
(4, 'Modem ADSL Wi-Fi', 'white', 'Navigazione senza fili piu'' veloce<br>\r\nConnessione di vari dispositivi<br>\r\nInstallazione semplice<br>\r\nFunzione Eco per risparmio energetico', '\r\nTecnologia<br>\r\n\r\n\r\n\r\n\r\nADSL/ADSL2+; velocità fino a 20 Mbps down/1 Mbps up<br><br>\r\n\r\n\r\n\r\n\r\nWi-Fi<br>\r\n\r\n\r\n\r\n\r\nWi-Fi 802.11 b/g/n; velocità di trasferimento fino a 300Mbps<br><br>\r\n\r\n\r\n\r\n\r\nInterfacce<br>\r\n\r\n\r\n\r\n\r\nInterfacce USB alta velocità (480 Mbit/s) ad alta potenza (500 mA), 1 porta connettore tipo A Interfaccia Wi-FiStandard IEEE 802.11nInterfaccia radio 2.4Ghz, 2 antenne, velocità di trasmissione teorica 300 Mbps<br><br>\r\n\r\n\r\n\r\n\r\nProtezione Wireless<br>\r\n\r\n\r\n\r\n\r\nWPA, WPA-PSK, WEP - Supporto Wi-Fi Protected Setup - Controllo di accesso<br><br>\r\n\r\n\r\n\r\n\r\nFunzioni avanzate<br>\r\n\r\n\r\n\r\n\r\nFunzionalità di routing avanzate (DHCP server, NAT, NAPT, Virtual Server) - Firewall - Condivisione Hard Disk e Stampante USB<br><br>\r\n\r\n\r\n\r\n\r\nAssistenza tecnica<br>\r\n\r\n\r\n\r\n\r\n2 anni di garanzia sul prodotto<br><br>\r\n\r\n\r\n\r\n\r\nContenuto della confezione<br>\r\n\r\n\r\n\r\n\r\nGuida di installazione; CD autoinstallante (compatibile con Windows 7, Vista, XP- MacOS 10.3); 1 filtro ADSL 2+; 1 cavo Telefonico; 1 cavo Ethernet\r\n', 69.99, 'modem4-front.jpg', '', ''),
(5, 'Modem WI-FI TIM 42.2 ', 'white', 'Design verticale compatto<br>\r\nWi-Fi AC 4x4 ad altissime prestazioni<br>\r\nAssociazione al modem in modalità WPS<br>\r\nDue porte Gigabit Ethernet<br>\r\nLed di stato<br>\r\n', '\r\nTecnologia<br>\r\n\r\n\r\n\r\n\r\nWi-Fi IEEE 802.11ac 5 GHz 4x4<br><br>\r\n\r\n\r\n\r\n\r\nInterfacce<br>\r\n\r\n\r\n\r\n\r\n2 Porte Ethernet<br><br>\r\n\r\n\r\n\r\n\r\nContenuto della confezione<br>\r\n\r\n\r\n\r\n\r\nMultimedia Connect; Alimentatore; Cavo Ethernet; Guida rapida; Garanzia di conformita''; Foglio di sicurezza<br><br>\r\n', 69.99, 'modem5-front.jpg', '', ''),
(6, 'TIM Modem Wi-Fi 4GPLUS ', 'white', 'Navigazione senza fili piu'' veloce<br>\r\nConnessione di vari dispositivi<br>\r\nInstallazione semplice<br>\r\nFunzione Eco per risparmio energetico', '\r\nTecnologia<br>\r\n\r\n\r\n\r\n\r\nADSL/ADSL2+; velocità fino a 20 Mbps down/1 Mbps up<br><br>\r\n\r\n\r\n\r\n\r\nWi-Fi<br>\r\n\r\n\r\n\r\n\r\nWi-Fi 802.11 b/g/n; velocità di trasferimento fino a 300Mbps<br><br>\r\n\r\n\r\n\r\n\r\nInterfacce<br>\r\n\r\n\r\n\r\n\r\nInterfacce USB alta velocità (480 Mbit/s) ad alta potenza (500 mA), 1 porta connettore tipo A Interfaccia Wi-FiStandard IEEE 802.11nInterfaccia radio 2.4Ghz, 2 antenne, velocità di trasmissione teorica 300 Mbps<br><br>\r\n\r\n\r\n\r\n\r\nProtezione Wireless<br>\r\n\r\n\r\n\r\n\r\nWPA, WPA-PSK, WEP - Supporto Wi-Fi Protected Setup - Controllo di accesso<br><br>\r\n\r\n\r\n\r\n\r\nFunzioni avanzate<br>\r\n\r\n\r\n\r\n\r\nFunzionalità di routing avanzate (DHCP server, NAT, NAPT, Virtual Server) - Firewall - Condivisione Hard Disk e Stampante USB<br><br>\r\n\r\n\r\n\r\n\r\nAssistenza tecnica<br>\r\n\r\n\r\n\r\n\r\n2 anni di garanzia sul prodotto<br><br>\r\n\r\n\r\n\r\n\r\nContenuto della confezione<br>\r\n\r\n\r\n\r\n\r\nGuida di installazione; CD autoinstallante (compatibile con Windows 7, Vista, XP- MacOS 10.3); 1 filtro ADSL 2+; 1 cavo Telefonico; 1 cavo Ethernet\r\n', 99.99, 'modem6-front.jpg', '', '');

-- --------------------------------------------------------

--
-- Struttura della tabella `servizi`
--

CREATE TABLE IF NOT EXISTS `servizi` (
  `id` int(11) NOT NULL,
  `nome` varchar(30) NOT NULL,
  `caratteristiche` longtext NOT NULL,
  `attivazione` longtext NOT NULL,
  `prezzo` double NOT NULL,
  `immagine_head` varchar(40) NOT NULL,
  `copertina` varchar(30) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `servizi`
--

INSERT INTO `servizi` (`id`, `nome`, `caratteristiche`, `attivazione`, `prezzo`, `immagine_head`, `copertina`) VALUES
(0, 'TIM Vision', 'Con il decoder TIMvision hai a disposizione piu'' di 8.000 titoli tra cartoni, film, serie e documentari sempre on demand per creare il tuo palinsesto senza interruzioni pubblicitarie.<br><br>\r\n\r\nTramite il telecomando puoi mettere in pausa il tuo film preferito e farlo ripartire quando decidi tu, puoi rivedere una scena o andare avanti.<br><br>\r\n\r\nCollega il decoder alla tua linea ADSL Illimitata o Fibra Ottica di TIM per accedere:<br><br>\r\n\r\nAl Videostore di TIMvision, dove ti aspettano tutti gli episodi delle migliori serie, dalle più famose alle più esclusive, i cartoni animati e le serie preferite per bambini e ragazzi, le anteprime piu'' attese e tanti film mai visti in tv o da rivedere in lingua originale. Scegli tra oltre 6.000 titoli sempre aggiornati.<br><br>\r\nAlla Replay TV di TIMvision, dove trovi tutti i programmi televisivi andati in onda negli ultimi 7 giorni sulle reti RAI (da tutti i dispositivi escluso streaming da web) e LA7 e l''archivio LA7<br><br>\r\nA YouTube, per vedere i video che vuoi direttamente dalla tua TV<br><br>\r\nPuoi goderti la visione anche su Smart TV, su timvision.it e su app TIMvision per Smartphone, Tablet e PC, utilizzando le credenziali scelte al momento della registrazione al servizio TIMvision.', 'Per l''attivazione di questo prodotto e'' sufficiente possedere il decoder TIM VIsion', 49.99, 'SL-1-head.png', 'SL_1_1.png'),
(1, 'TIM Sky', 'Per te il grande spettacolo e l''innovazione di Sky a partire da soli 14 euro/mese in più per i primi 18 mesi.<br><br>\r\n\r\nSe aderisci a TIM Sky entro il 3 luglio 2016 puoi avere:<br><br>\r\n\r\nMy Sky per vedere la TV come e quando vuoi e Sky On Demand, una videoteca con migliaia di titoli sempre a tua disposizione.<br><br>\r\n\r\nSky TV con 38 canali di intrattenimento esclusivo a soli 14 euro/mese per i primi 18 mesi, oppure Sky TV + un pacchetto a scelta tra Sky Cinema, Sky Sport o Sky Calcio a 26,90 euro/mese per i primi 18 mesi. Puoi aggiungere all''offerta anche Sky Famiglia + Sky HD a 5 euro/mese per i primi 18 mesi anziche'' 11€.\r\n\r\nSky Box Sets e'' la novità di Sky che ti offre le migliori serie TV, stagione dopo stagione, tutte su My Sky.<br><br>\r\n\r\nIn piu'' puoi avere Sky Link per collegare My Sky in Wi-Fi a 30 euro.<br><br>\r\n\r\nSe sei cliente ADSL, avrai inclusi nell''offerta:<br><br>\r\n\r\nSuperinternet Plus, per navigare fino a 20 Mega<br>\r\nSMART MODEM', '14 euro/mese in più per 18 mesi con Sky TV e 12 mesi di Sky Box Sets.<br><br>\r\n\r\nOPPURE 19 euro/mese per i primi 18 mesi con Sky Famiglia + Sky HD<br><br>\r\n\r\nOPPURE 26,90 euro/mese per i primi 18 mesi con un pacchetto a scelta tra Sky Cinema, Sky Sport o Sky Calcio<br><br>\r\n\r\nOPPURE 31,90 euro/mese per i primi 18 mesi con Sky Famiglia + Sky HD + un pacchetto a scelta tra Sky Cinema, Sky Sport o Sky Calcio<br><br>\r\n\r\nOFFERTA SKY DISPONIBILE ANCHE PER GIA'' CLIENTI SKY', 149.99, 'SL-2-head.jpg', 'SL_1_2.png'),
(2, 'Netflix', 'Hai la possibilita'' di guardare in streaming migliaia di programmi televisivi e film, quando vuoi e dove vuoi, sulla tua TV mediante il decoder TIMvision, su Smart TV, PS3, PS4,Wii, Xbox, PC, Mac, smartphone, tablet.<br><br>\r\n\r\nAbbonandoti al servizio NETFLIX da decoder TIMvision collegato alla linea adsl/fibra di casa hai la possibilita'' di addebitare il costo di Netflix direttamente sulla tua fattura di linea fissa TIM. Con Netflix non ci sono spot pubblicitari, puoi mettere in pausa, tornare indietro o riprendere la visione tutte le volte che vorrai, senza alcun limite. Non ci sono impegni, potrai cessare il tuo abbonamento a Netflix in ogni momento.', 'Con TIM accedi al mondo Netflix in maniera facile e immediata con il decoder TIMvision. Per i clienti TIM non occorre alcuna carta di credito per Netflix. Paghi comodamente sulla fattura TIM e mantieni sotto controllo le spese. Puoi guardare Netflix in qualsiasi momento, senza interruzioni pubblicitarie. Un''esperienza facile e veloce con tre pacchetti da scegliere in abbonamento.<br><br>\r\n\r\nProva il tuo mese GRATIS.', 11.99, 'SL-3-head.jpg', 'SL_1_3.png'),
(3, 'TIM Premium Online', '18 Canali in live streaming e un catalogo con oltre 8000 titoli on demand, inclusi i contenuti di Infinity, anche in HD, con doppio audio e sottotitoli.<br><br>\r\n\r\nCentinaia di film e serie tv in anteprima e in esclusiva. Tutta la UEFA Champions League (2015-2018) in esclusiva, la Serie A Tim delle squadre Premium, i campionati esteri, il FIA World Rally Championship 2016, il meglio dell''intrattenimento di Mediaset e molto altro ancora!', 'Se sei già cliente TIM ADSL con opzione Superinternet attiva, in caso di attivazione di TIM Premium Online, il costo dell''opzione verra'' scontato dal tuo abbonamento. \r\nLa cessazione del servizio Premium Online comporterà il venir meno della gratuita'' dell''abbonamento Superinternet che, verra'' addebitato e fatturato al prezzo di listino TIM in vigore a partire dalla data di cessazione del servizio Premium Online. L''attivazione dell''offerta TIM Premium Online presuppone la sottoscrizione di due distinti contratti, uno con TIM e uno con MEDIASET, ciascuno regolato dalle rispettive condizioni generali di contratto.', 34.99, 'SL-4-head.jpg', 'SL_1_4.png'),
(4, 'Chromecast', 'Con Chromecast, il tuo telefono diventa un telecomando. Cerca e riproduci i tuoi contenuti preferiti sullo schermo della TV, metti in pausa e altro ancora, direttamente dal tuo smartphone.<br><br>\r\n\r\nPuoi scegliere tra migliaia di programmi TV e film, milioni di brani, nonché radio, sport, giochi e altro ancora. Scopri tutte le app compatibili all''indirizzo chromecast.com/apps.<br><br>\r\n\r\nAccedendo all''app Chromecast puoi trasmettere allo schermo della TV i contenuti che vedi sul tuo telefono o tablet Android compatibile semplicemente selezionando la funzione "Trasmetti schermo/audio". Se invece utilizzi il browser Chrome dal tuo laptop, ti basta scaricare l''estensione Google Cast per trasmettere qualsiasi sito web.', 'Per attivare l''offerta puoi acquistare direttamente online o  presso i Negozi TIM il Pack TIMvision&Chromecast  che include Chromecast ed in promozione 3 mesi di  TIMvision in abbonamento.', 39.99, 'SL-5-head.jpg', 'SL_1_5.png');

-- --------------------------------------------------------

--
-- Struttura della tabella `sl_for_devices`
--

CREATE TABLE IF NOT EXISTS `sl_for_devices` (
  `id_serv` int(5) NOT NULL,
  `id_dev` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_serv`,`id_dev`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `sl_for_devices`
--

INSERT INTO `sl_for_devices` (`id_serv`, `id_dev`) VALUES
(0, 1000),
(1, 1000),
(2, 1),
(2, 10),
(2, 1000),
(3, 1),
(3, 1000),
(3, 2000),
(4, 4),
(4, 5),
(4, 3000);

-- --------------------------------------------------------

--
-- Struttura della tabella `tablet`
--

CREATE TABLE IF NOT EXISTS `tablet` (
  `id` int(11) NOT NULL,
  `nome` varchar(30) NOT NULL,
  `colore` varchar(30) NOT NULL,
  `caratteristiche` varchar(200) NOT NULL,
  `specifiche` longtext NOT NULL,
  `prezzo` double NOT NULL,
  `immagine_front` varchar(40) NOT NULL,
  `immagine_back` varchar(40) NOT NULL,
  `immagine_side` varchar(40) NOT NULL,
  `promozione` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`,`nome`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `tablet`
--

INSERT INTO `tablet` (`id`, `nome`, `colore`, `caratteristiche`, `specifiche`, `prezzo`, `immagine_front`, `immagine_back`, `immagine_side`, `promozione`) VALUES
(1, 'HUAWEI MediaPad 10 LINK+', 'white', 'Display 10.1" (1280x800) IPS 16M di colori<br>\r\nSistema Operativo Android 4.2.2 JB\r\n', '\r\nConnettivita<br>\r\n\r\n\r\n\r\n\r\nHSDPA+ 42.2Mbps/HSUPA 5.76/, Wi-Fi 802.11b/g/n, Bluetooth 3.0<br><br>\r\n\r\n\r\n\r\n\r\nDisplay<br>\r\n\r\n\r\n\r\n\r\n10.1" (1280x800) IPS 16M di colori<br><br>\r\n\r\n\r\n\r\n\r\nVideo/Audio/Picture<br>\r\n\r\n\r\n\r\n\r\n2 Fotocamera da 3 Mpx e VGA Lettore multimediale - MP3, WAV, 3GP, AAC, AAC+ e-AAC+, JPG, PNG,GIF, BMP, WMV, H264, Mpeg4, 1080p/30fps<br><br>\r\n\r\n\r\n\r\n\r\nMemoria<br>\r\n\r\n\r\n\r\n\r\n8GB (espandibile fino a 32GB)<br><br>\r\n\r\n\r\n\r\n\r\nProcessore<br>\r\n\r\n\r\n\r\n\r\nBalon Cortex A9 Quad-Core 1.6GHz<br><br>\r\n\r\n\r\n\r\n\r\nSistemaOperativo<br>\r\n\r\n\r\n\r\n\r\nAndroidTM 4.2.2 Jelly Bean<br><br>\r\n\r\n\r\n\r\n\r\nApplicazioni<br>\r\n\r\n\r\n\r\n\r\nGoogle Mobile Services, Youtube, E-mail, GPS e A-GPS, SMS, Invio e ricezione, chiamata voce.<br><br>\r\n\r\n\r\n\r\n\r\nIn dotazione<br>\r\n\r\n\r\n\r\n\r\nCaricabatteria - Manuale d''uso<br><br>\r\n\r\n\r\n\r\n\r\nDimensioni<br>\r\n\r\n\r\n\r\n\r\n257.4x175.9x9.9mm<br><br>\r\n\r\n\r\n\r\n\r\nPeso<br>\r\n\r\n\r\n\r\n\r\n630 grammi<br><br>\r\n\r\n\r\n\r\n\r\nAutonomia (*)<br>\r\n\r\n\r\n\r\n\r\nStand-by fino a 600h<br><br>\r\n\r\n\r\n\r\n\r\nNote<br>\r\n\r\n\r\n\r\n\r\n* Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.\r\n', 199.99, 'tablet1-front.jpg', 'tablet1-back.jpg', 'tablet1-side.jpg', 0),
(2, 'Apple iPad Pro 128 GB', 'black,white', 'Sistema Operativo iOS 9<br>\r\nRetina Display 12.9" (2732x2048) Led IPS<br>\r\nA9X con architettura a 64bit a 1.6GHz<br>\r\nFotocamera iSight da 8 megapixel<br>', '\r\nDisplay<br>\r\n\r\n\r\n\r\n\r\nRetina Display 12.9"<br><br>\r\n\r\n\r\n\r\n\r\nSensori<br>\r\n\r\n\r\n\r\n\r\nimpronte digitali Touch ID<br><br>\r\n\r\n\r\n\r\n\r\nProcessore<br>\r\n\r\n\r\n\r\n\r\nco-processore M9<br><br>\r\n\r\n\r\n\r\n\r\nFotocamera<br>\r\n\r\n\r\n\r\n\r\niSight da 8MP<br><br>\r\n\r\n\r\n\r\n\r\nVideocamera<br>\r\n\r\n\r\n\r\n\r\nFaceTime HD<br><br>\r\n\r\n\r\n\r\n\r\nConnettivita<br>\r\n\r\n\r\n\r\n\r\nLTE /HSDPA-DC 42.2/HSUPA 5.76/, Wi-Fi 802.11a/b/g/n/ac e MIMO, Bluetooth 4.2<br><br>\r\n\r\n\r\n\r\n\r\nBatteria<br>\r\n\r\n\r\n\r\n\r\nFino a 10 ore di autonomia1<br><br>\r\n\r\n\r\n\r\n\r\nNote<br>\r\n\r\n\r\n\r\n\r\n1 - La durata della batteria varia a seconda dell''uso e della configurazione. Vai su <a>www.apple.com/it/batteries</a> per saperne di piu''.<br>\r\n\r\n2 - Richiede un piano dati. La tecnologia 4G LTE e'' supportata solo in alcuni Paesi e solo da alcuni operatori. La velocita'' varia a seconda delle condizioni ambientali.\r\n', 1249.99, 'tablet2-front.jpg', 'tablet2-back.jpg', 'tablet2-side.jpg', 1),
(3, 'Samsung Galaxy TAB A 9.7', 'black,white', 'Display 9.7" TFT<br>\r\nSistema Operativo Android 5.0', '\r\nDisplay<br>\r\n\r\n\r\n9.7" TFT,1024x768 (4:3) <br><br>\r\n\r\n\r\nProcessore<br>\r\n\r\n\r\nSnapdragon 410 QuadCore da 1.2 GHz <br><br>\r\n\r\n\r\n\r\nMemoria<br>\r\n\r\n\r\nInterna 16GB (espandibile fino a 128GB), 2GB di Ram <br><br>\r\n\r\n\r\n\r\nTecnologia<br>\r\n\r\n\r\nLTE/HSDPA/HSUPA <br><br>\r\n\r\n\r\n\r\nConnettivita<br>\r\n\r\n\r\nWi-Fi 802.11 a/b/g/n - Bluetooth 4.0 - micro USB <br><br>\r\n\r\n\r\n\r\nSistemaOperativo<br>\r\n\r\n\r\nAndroid™ 5.0.2 <br><br>\r\n\r\n\r\n\r\nApplicazioni<br>\r\n\r\n\r\nAndroid Market, Google Mobile App, Youtube, Inserimento testo e ricerca vocale, E-mail, A-GPS, SMS/MMS <br><br>\r\n\r\n\r\nFotocamera<br>\r\n\r\n\r\nFront: 2 Mpxl - Back: 5 Mpxl <br><br>\r\n\r\n\r\n\r\nLettore Multimediale<br>\r\n\r\n\r\naac,amr,awb,mp3,ogg,wav, DivX, XviD, MPEG4, VP8, H.263, H.264 <br><br>\r\n\r\n\r\n\r\nDimensioni<br>\r\n\r\n\r\n242,5 x 166,8 x 7,4 mm <br><br>\r\n\r\n\r\n\r\nPeso<br>\r\n\r\n\r\n455 grammi <br><br>\r\n\r\n\r\n\r\nAutonomia<br>\r\n\r\n\r\nStand-by fino a 250h - 43 ore in chiamata <br><br>\r\n\r\n\r\n\r\nIn dotazione<br>\r\n\r\n\r\nCarica batteria - Manuale d''uso - Cavo dati USB\r\n', 299.99, 'tablet3-front.jpg', 'tablet3-back.jpg', 'tablet3-side.jpg', 1),
(4, 'Huawei Mediapad T1 10 LTE', 'white', 'Display 10.1" (1280x800) IPS 16M di colori<br>\r\nSistema Operativo Android 4.2.2 JB\r\n', '\r\nConnettivita<br>\r\n\r\n\r\n\r\n\r\nHSDPA+ 42.2Mbps/HSUPA 5.76/, Wi-Fi 802.11b/g/n, Bluetooth 3.0<br><br>\r\n\r\n\r\n\r\n\r\nDisplay<br>\r\n\r\n\r\n\r\n\r\n10.1" (1280x800) IPS 16M di colori<br><br>\r\n\r\n\r\n\r\n\r\nVideo/Audio/Picture<br>\r\n\r\n\r\n\r\n\r\n2 Fotocamera da 3 Mpx e VGA Lettore multimediale - MP3, WAV, 3GP, AAC, AAC+ e-AAC+, JPG, PNG,GIF, BMP, WMV, H264, Mpeg4, 1080p/30fps<br><br>\r\n\r\n\r\n\r\n\r\nMemoria<br>\r\n\r\n\r\n\r\n\r\n8GB (espandibile fino a 32GB)<br><br>\r\n\r\n\r\n\r\n\r\nProcessore<br>\r\n\r\n\r\n\r\n\r\nBalon Cortex A9 Quad-Core 1.6GHz<br><br>\r\n\r\n\r\n\r\n\r\nSistemaOperativo<br>\r\n\r\n\r\n\r\n\r\nAndroidTM 4.2.2 Jelly Bean<br><br>\r\n\r\n\r\n\r\n\r\nApplicazioni<br>\r\n\r\n\r\n\r\n\r\nGoogle Mobile Services, Youtube, E-mail, GPS e A-GPS, SMS, Invio e ricezione, chiamata voce.<br><br>\r\n\r\n\r\n\r\n\r\nIn dotazione<br>\r\n\r\n\r\n\r\n\r\nCaricabatteria - Manuale d''uso<br><br>\r\n\r\n\r\n\r\n\r\nDimensioni<br>\r\n\r\n\r\n\r\n\r\n257.4x175.9x9.9mm<br><br>\r\n\r\n\r\n\r\n\r\nPeso<br>\r\n\r\n\r\n\r\n\r\n630 grammi<br><br>\r\n\r\n\r\n\r\n\r\nAutonomia (*)<br>\r\n\r\n\r\n\r\n\r\nStand-by fino a 600h<br><br>\r\n\r\n\r\n\r\n\r\nNote<br>\r\n\r\n\r\n\r\n\r\n* Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.\r\n', 249.99, 'tablet4-front.jpg', 'tablet4-back.jpg', 'tablet4-side.jpg', 0),
(5, 'Samsung Galaxy TabPro S 12', 'black', 'Display 9.7" TFT<br>\r\nSistema Operativo Android 5.0', '\r\nDisplay<br>\r\n\r\n\r\n9.7" TFT,1024x768 (4:3) <br><br>\r\n\r\n\r\nProcessore<br>\r\n\r\n\r\nSnapdragon 410 QuadCore da 1.2 GHz <br><br>\r\n\r\n\r\n\r\nMemoria<br>\r\n\r\n\r\nInterna 16GB (espandibile fino a 128GB), 2GB di Ram <br><br>\r\n\r\n\r\n\r\nTecnologia<br>\r\n\r\n\r\nLTE/HSDPA/HSUPA <br><br>\r\n\r\n\r\n\r\nConnettivita<br>\r\n\r\n\r\nWi-Fi 802.11 a/b/g/n - Bluetooth 4.0 - micro USB <br><br>\r\n\r\n\r\n\r\nSistemaOperativo<br>\r\n\r\n\r\nAndroid™ 5.0.2 <br><br>\r\n\r\n\r\n\r\nApplicazioni<br>\r\n\r\n\r\nAndroid Market, Google Mobile App, Youtube, Inserimento testo e ricerca vocale, E-mail, A-GPS, SMS/MMS <br><br>\r\n\r\n\r\nFotocamera<br>\r\n\r\n\r\nFront: 2 Mpxl - Back: 5 Mpxl <br><br>\r\n\r\n\r\n\r\nLettore Multimediale<br>\r\n\r\n\r\naac,amr,awb,mp3,ogg,wav, DivX, XviD, MPEG4, VP8, H.263, H.264 <br><br>\r\n\r\n\r\n\r\nDimensioni<br>\r\n\r\n\r\n242,5 x 166,8 x 7,4 mm <br><br>\r\n\r\n\r\n\r\nPeso<br>\r\n\r\n\r\n455 grammi <br><br>\r\n\r\n\r\n\r\nAutonomia<br>\r\n\r\n\r\nStand-by fino a 250h - 43 ore in chiamata <br><br>\r\n\r\n\r\n\r\nIn dotazione<br>\r\n\r\n\r\nCarica batteria - Manuale d''uso - Cavo dati USB\r\n', 1299.99, 'tablet5-front.jpg', 'tablet5-back.jpg', 'tablet5-side.jpg', 0),
(6, 'Apple iPad mini 4 16GB', 'black,white', 'Sistema Operativo iOS 9<br>\r\nRetina Display 12.9" (2732x2048) Led IPS<br>\r\nA9X con architettura a 64bit a 1.6GHz<br>\r\nFotocamera iSight da 8 megapixel<br>', '\r\nDisplay<br>\r\n\r\n\r\n\r\n\r\nRetina Display 12.9"<br><br>\r\n\r\n\r\n\r\n\r\nSensori<br>\r\n\r\n\r\n\r\n\r\nimpronte digitali Touch ID<br><br>\r\n\r\n\r\n\r\n\r\nProcessore<br>\r\n\r\n\r\n\r\n\r\nco-processore M9<br><br>\r\n\r\n\r\n\r\n\r\nFotocamera<br>\r\n\r\n\r\n\r\n\r\niSight da 8MP<br><br>\r\n\r\n\r\n\r\n\r\nVideocamera<br>\r\n\r\n\r\n\r\n\r\nFaceTime HD<br><br>\r\n\r\n\r\n\r\n\r\nConnettivita<br>\r\n\r\n\r\n\r\n\r\nLTE /HSDPA-DC 42.2/HSUPA 5.76/, Wi-Fi 802.11a/b/g/n/ac e MIMO, Bluetooth 4.2<br><br>\r\n\r\n\r\n\r\n\r\nBatteria<br>\r\n\r\n\r\n\r\n\r\nFino a 10 ore di autonomia1<br><br>\r\n\r\n\r\n\r\n\r\nNote<br>\r\n\r\n\r\n\r\n\r\n1 - La durata della batteria varia a seconda dell''uso e della configurazione. Vai su <a>www.apple.com/it/batteries</a> per saperne di piu''.<br>\r\n\r\n2 - Richiede un piano dati. La tecnologia 4G LTE e'' supportata solo in alcuni Paesi e solo da alcuni operatori. La velocita'' varia a seconda delle condizioni ambientali.\r\n', 529.99, 'tablet6-front.jpg', 'tablet6-back.jpg', 'tablet6-side.jpg', 0);

-- --------------------------------------------------------

--
-- Struttura della tabella `telefoni`
--

CREATE TABLE IF NOT EXISTS `telefoni` (
  `id` int(11) NOT NULL,
  `nome` varchar(30) NOT NULL,
  `colore` varchar(30) NOT NULL,
  `caratteristiche` varchar(200) NOT NULL,
  `specifiche` longtext NOT NULL,
  `prezzo` double NOT NULL,
  `immagine_front` varchar(40) NOT NULL,
  `immagine_back` varchar(40) NOT NULL,
  `immagine_side` varchar(40) NOT NULL,
  `promozione` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`,`nome`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `telefoni`
--

INSERT INTO `telefoni` (`id`, `nome`, `colore`, `caratteristiche`, `specifiche`, `prezzo`, `immagine_front`, `immagine_back`, `immagine_side`, `promozione`) VALUES
(1, 'Samsung Galaxy S7', 'black,white,gold', 'Sistema Operativo Android 6.0<br>\r\nDisplay 5.5''''<br>\r\nProcessore OctaCore (QuadCore 2.3 Ghz + QuadCore 1.6 Ghz)', 'Tecnologia<br>\r\n4G cat.9/HSDPA42UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100\r\n<br><br>\r\nConnettivita<br>\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n<br><br>\r\nGPS<br>\r\nIntegrato\r\n<br><br>\r\nDisplay<br>\r\n5.5'''' 16 Milioni colori Touch\r\n<br><br>\r\nFotocamera<br>\r\n12 Mpixel/Flash\r\n<br><br>\r\nMemoria Interna<br>\r\n32GB\r\n<br><br>\r\nProcessore<br>\r\nOctaCore: (QuadCore 2.3 Ghz+QuadCore 1.6 Ghz)\r\n<br><br>\r\nFormato SIM<br>\r\nNano\r\n<br><br>\r\nVideo<br>\r\nVideo Recorder&Playback\r\n<br><br>\r\nMusica<br>\r\nMP3 Player\r\n<br><br>\r\nIn dotazione<br>\r\nCaricabatteria - Cavo Dati MicroUSB - Auricolare stereo - Guida di riferimento rapido\r\n<br><br>\r\nDimensioni<br>\r\n150,9x72,6x7,7 mm\r\n<br><br>\r\nPeso<br>\r\n157 gr.\r\n<br><br>\r\nAutonomia(*)<br>\r\nStand-by fino a TBD ore - Conversazione fino a TBD min\r\n<br><br>\r\nNote<br>\r\n* Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.', 729.99, 's7-front.jpg', 's7-back.jpg', 's7-side.jpg', 1),
(2, 'Samsung Galaxy J5', 'black,white,gold', 'Sistema Operativo Android 5.1<br>\r\nDisplay 5.2" 16 Milioni colori Touch<br>\r\nProcessore QuadCore 1.2 Ghz', 'Tecnologia<br>\r\n4G/HSDPA42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100\r\n<br><br>\r\nConnettivita<br>\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n<br><br>\r\nGPS<br>\r\nRicevitore GPS Integrato\r\n<br>\r\nDisplay<br>\r\nDisplay 5.2” 16 Milioni colori Touch\r\n<br><br>\r\nFotocamera<br>\r\nFotocamera 13 Mpixel/Flash\r\n<br><br>\r\nMemoria<br>\r\nMemoria interna 16GB - Slot Memory Card Micro SD fino a 128GB\r\n<br><br>\r\nProcessore<br>\r\nProcessore QuadCore 1.2 Ghz\r\n<br><br>\r\nFormato SIM<br>\r\nSIM Micro\r\n<br><br>\r\nVideo<br>\r\nVideo Recorder&Playback\r\n<br><br>\r\nMusica<br>\r\nMP3 Player - Radio FM\r\n<br><br>\r\nIn dotazione<br>\r\nCaricabatteria - Cavo dati - Auricolare - Manuale d’uso rapido\r\n<br><br>\r\nDimensioni<br>\r\n145,8x72,3x8,1 mm\r\n<br><br>\r\nPeso<br>\r\n158 gr\r\n<br><br>\r\nNote\r\n* Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.', 229.99, 'galaxyj5-front.png', 'galaxyj5-back.jpg', 'galaxyj5-side.jpg', 0),
(3, 'Sony XPERIA X', 'black', 'Sistema Operativo Android 6.0<br>\r\nProcessore Snapdragon 650 HexaCore 1.8 Ghz + 1.4 Ghz', 'Tecnologia<br>\r\nAbilitato tecnologia 4G/HSDPA 42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900\r\n<br><br>\r\nConnettivita<br>\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n<br><br>\r\nGPS<br>\r\nIntegrato\r\n<br><br>\r\nDisplay<br>\r\nFull HD da 5'''' 1080p, Display TRILUMINOS\r\n<br><br>\r\nFotocamera<br>\r\nPosteriore da 23 Mpixel Exmor, Anteriore da 13 Mpxl\r\n<br><br>\r\nMemoria<br>\r\nInterna 3GB - Slot Memory Card Micro SD fino a 200GB\r\n<br><br>\r\nProcessore<br>\r\nProcessore Qualcomm Snapdragon 650 Hexa-Core (1.8 GHz + 1.4 GHz)\r\n<br><br>\r\nVideo<br>\r\nVideo Recorder&Playback\r\n<br><br>\r\nMusica<br>\r\nMP3 Player - Radio FM\r\n<br><br>\r\nIn dotazione<br>\r\nAuricolare stereo - Caricabatteria - Cavo dati - Guida di riferimento rapido\r\n<br><br>\r\nDimensioni<br>\r\n143,7 x 70,5 x 8,6 mm\r\n<br><br>\r\nPeso<br>\r\n165 grammi\r\n<br><br>\r\nAutonomia<br>\r\nStand-by fino a 779 ore - Conversazione fino a 790 min', 629.99, 'sony-xperia-x-front.jpg', 'sony-xperia-x-back.jpg', 'sony-xperia-x-side.jpg', 1),
(4, 'LG G5', 'black,white', 'Sistema Operativo Android 6.0<br>\r\nProcessore Snapdragon 650 HexaCore 1.8 Ghz + 1.4 Ghz', 'Tecnologia<br>\r\n4G cat.9/HSDPA42UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100\r\n<br><br>\r\nConnettivita<br>\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n<br><br>\r\nGPS<br>\r\nIntegrato\r\n<br><br>\r\nDisplay<br>\r\n5.5'''' 16 Milioni colori Touch\r\n<br><br>\r\nFotocamera<br>\r\n12 Mpixel/Flash\r\n<br><br>\r\nMemoria Interna<br>\r\n32GB\r\n<br><br>\r\nProcessore<br>\r\nOctaCore: (QuadCore 2.3 Ghz+QuadCore 1.6 Ghz)\r\n<br><br>\r\nFormato SIM<br>\r\nNano\r\n<br><br>\r\nVideo<br>\r\nVideo Recorder&Playback\r\n<br><br>\r\nMusica<br>\r\nMP3 Player\r\n<br><br>\r\nIn dotazione<br>\r\nCaricabatteria - Cavo Dati MicroUSB - Auricolare stereo - Guida di riferimento rapido\r\n<br><br>\r\nDimensioni<br>\r\n150,9x72,6x7,7 mm\r\n<br><br>\r\nPeso<br>\r\n157 gr.\r\n<br><br>\r\nAutonomia(*)<br>\r\nStand-by fino a TBD ore - Conversazione fino a TBD min\r\n<br>\r\nNote\r\n* Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.', 699.99, 'LG-G5-front.jpg', 'LG-G5-back.jpg', 'LG-G5-side.jpg', 0),
(5, 'Huawei P9 Plus', 'black,white', 'Sistema Operativo Android 6.0<br>\r\nProcessore Snapdragon 650 HexaCore 1.8 Ghz + 1.4 Ghz', 'Tecnologia<br>\r\n4G cat.9/HSDPA42UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100\r\n<br><br>\r\nConnettivita<br>\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n<br><br>\r\nGPS<br>\r\nIntegrato\r\n<br><br>\r\nDisplay<br>\r\n5.5'''' 16 Milioni colori Touch\r\n<br><br>\r\nFotocamera<br>\r\n12 Mpixel/Flash\r\n<br><br>\r\nMemoria Interna<br>\r\n32GB\r\n<br><br>\r\nProcessore<br>\r\nOctaCore: (QuadCore 2.3 Ghz+QuadCore 1.6 Ghz)\r\n<br><br>\r\nFormato SIM<br>\r\nNano\r\n<br><br>\r\nVideo<br>\r\nVideo Recorder&Playback\r\n<br><br>\r\nMusica<br>\r\nMP3 Player\r\n<br><br>\r\nIn dotazione<br>\r\nCaricabatteria - Cavo Dati MicroUSB - Auricolare stereo - Guida di riferimento rapido\r\n<br><br>\r\nDimensioni<br>\r\n150,9x72,6x7,7 mm\r\n<br><br>\r\nPeso<br>\r\n157 gr.\r\n<br><br>\r\nAutonomia(*)<br>\r\nStand-by fino a TBD ore - Conversazione fino a TBD min\r\n<br>\r\nNote\r\n* Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.', 649.99, 'p9-front.jpg', 'p9-back.jpg', 'p9-side.jpg', 0),
(6, 'Apple iPhone SE', 'black,white', 'Sistema Operativo iOS 6.0<br>\r\nProcessore Snapdragon® 650 HexaCore 1.8 Ghz + 1.4 Ghz', 'Tecnologia<br>\r\nAbilitato tecnologia 4G/HSDPA 42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900\r\n<br><br>\r\nConnettivita<br>\r\nWi-Fi - Bluetooth - Micro USB - NFC\r\n<br><br>\r\nGPS<br>\r\nIntegrato\r\n<br><br>\r\nDisplay<br>\r\nFull HD da 5'''' 1080p, Display TRILUMINOS\r\n<br><br>\r\nFotocamera<br>\r\nPosteriore da 23 Mpixel Exmor, Anteriore da 13 Mpxl\r\n<br><br>\r\nMemoria<br>\r\nInterna 3GB - Slot Memory Card Micro SD fino a 200GB\r\n<br><br>\r\nProcessore<br>\r\nProcessore Qualcomm Snapdragon 650 Hexa-Core (1.8 GHz + 1.4 GHz)\r\n<br><br>\r\nVideo<br>\r\nVideo Recorder&Playback\r\n<br><br>\r\nMusica<br>\r\nMP3 Player - Radio FM\r\n<br><br>\r\nIn dotazione<br>\r\nAuricolare stereo - Caricabatteria - Cavo dati - Guida di riferimento rapido\r\n<br><br>\r\nDimensioni<br>\r\n143,7 x 70,5 x 8,6 mm\r\n<br><br>\r\nPeso<br>\r\n165 grammi\r\n<br><br>\r\nAutonomia<br>\r\nStand-by fino a 779 ore - Conversazione fino a 790 min', 509.99, 'manato-front.jpg', 'manato-back.jpg', 'manato-side.jpg', 1);

-- --------------------------------------------------------

--
-- Struttura della tabella `tv`
--

CREATE TABLE IF NOT EXISTS `tv` (
  `id` int(11) NOT NULL,
  `nome` varchar(30) NOT NULL,
  `colore` varchar(30) NOT NULL,
  `caratteristiche` varchar(200) NOT NULL,
  `specifiche` longtext NOT NULL,
  `prezzo` double NOT NULL,
  `immagine_front` varchar(40) NOT NULL,
  `immagine_back` varchar(40) NOT NULL,
  `immagine_side` varchar(40) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `tv`
--

INSERT INTO `tv` (`id`, `nome`, `colore`, `caratteristiche`, `specifiche`, `prezzo`, `immagine_front`, `immagine_back`, `immagine_side`) VALUES
(6, 'Samsung Gear Fit', 'black', 'Cassa in alluminio anodizzato color argento, grigio siderale<br>\r\nVetro rinforzato Ion-X<br>\r\nDisplay Retina con Force Touch<br>\r\nFondo in materiale composito<br>\r\nDigital Crown', '\r\nDisplay<br>\r\n\r\nVetro Ion-X<br>\r\n\r\nDisplay Retina con Force Touch<br><br>\r\n\r\n\r\nSensori<br>\r\n\r\nCardiofrequenzimetro<br>\r\n\r\nAccelerometro<br>\r\n\r\nGiroscopio<br>\r\n\r\nSensore di luce ambientale<br><br>\r\n\r\n\r\nConnettivita<br>\r\n\r\n\r\nWi-Fi (802.11b/g/n a 2,4GHz)<br>\r\n\r\nBluetooth 4.0<br><br>\r\n\r\n\r\nBatteria<br>\r\n\r\nFino a 18 ore di autonomia<br><br> \r\n\r\n\r\nResistenza all''acqua<br>\r\n\r\nSi\r\n', 79.99, 'tv6-front.jpg', 'tv6-back.jpg', 'tv6-side.jpg'),
(5, 'WeR@Home', 'white', 'Fruibile da smartphone, tablet e PC<br>\r\nFacile da installare e utilizzare<br>\r\nApp dedicata per iOS e Android\r\n', 'Il KIT comprende<br><br>\r\nCentralina<br>\r\n1 telecamera con sensore di movimento: immagini JPEG a colori<br>\r\n1 sensore apertura porta/finestra con sensori LED<br>\r\n6 MESI DI SERVIZIO WeR@Home GRATIS!<br><br>\r\n\r\nCARATTERISTICHE<br><br>\r\nDesign moderno ed elegante<br>\r\nInvio notifiche su smartphone/tablet/PC<br>\r\nInterfaccia WEB facile da utilizzare<br>\r\nApp dedicata per iOS e Android<br>\r\nAssistenza tecnica<br>\r\nSistema espandibile per adattarsi alle tue esigenze\r\n', 199.99, 'tv5-front.jpg', '', 'tv5-side.jpg'),
(4, 'TIMTag', 'white', 'Resistente all’acqua<br>\r\nFornisce allarmi di movimento (velocità, inerzia, crash)<br>\r\nBatteria di lunga durata<br>\r\nDimensioni 49 x 47 x 17 mm\r\n', 'L''offerta e'' rivolta a tutti i Clienti TIM Ricaricabili Consumer.<br><br>\r\n\r\nAll''attivazione della TIMCard viene attivata l''offerta Tim-Tag in promozione per 12 mesi.<br><br>\r\n\r\nL''offerta puo'' essere attivata solo sulla TIM Card contenuta all''interno della confezione.<br><br>\r\n\r\nIl traffico sia dati che sms del Tracker GPS vs la piattaforma di servizio, e'' incluso nell’opzione TIM Tag (50MB e 100SMS ogni 30 giorni). Il Bundle dati e sms previsto e'' calibrato per soddisfare le esigenze di un utilizzo continuativo del dispositivo.<br>\r\nPer fruire dell''offerta e'' in ogni caso necessario che la TIMCard ad essa associata disponga di un credito telefonico residuo, in quanto non puo'' essere effettuato traffico in assenza di credito sulla TIM Card.<br>\r\nPer effettuare il download sul proprio smartphone dell’APP TIMTag, e'' necessario avere connessione dati attiva o una copertura Wi-Fi.<br><br>\r\n\r\nL''app TIMTag e'' compatibile con dispositivi iOS e Android.<br><br>\r\n\r\nAlla scadenza (trascorsi 360 gg dall''attivazione di Servizio), salvo disdetta, l''opzione TIMTag restera'' attiva a 5 euro/mese con addebito su credito residuo della TIMCard. Pertanto si dovra'' fare attenzione a disporre di un credito residuo sufficiente di almeno 5 euro.<br><br>\r\n\r\nE'' possibile avere informazioni sul servizio e sullo stato delliutenza contattando il Servizio Assistenza Clienti 119.<br><br>\r\n\r\nIl Cliente potra'' recedere in qualsiasi momento dall''Offerta chiamando il Servizio Assistenza Clienti 119.<br><br>\r\n\r\nIl rilevatore GPS contenuto nella confezione e'' acquistato con effetto immediato e definitivo.\r\n', 129.99, 'tv4-front.jpg', '', 'tv4-side.jpg'),
(1, 'Samsung Smart TV 50"', 'black', 'Modello 50JU6400 - 50<br>\r\nUltra HD - 4K 3840 x 2160<br>\r\nSoundbar HW-J250 inclusa<br>\r\nTIMvision incluso<br>\r\n', '', 1699.99, 'tv1-front.jpg', 'tv1-back.jpg', 'tv1-side.jpg'),
(3, 'Apple Watch Sport 38', 'black', 'Cassa in alluminio anodizzato color argento, grigio siderale<br>\r\nVetro rinforzato Ion-X<br>\r\nDisplay Retina con Force Touch<br>\r\nFondo in materiale composito<br>\r\nDigital Crown', '\r\nDisplay<br>\r\n\r\nVetro Ion-X<br>\r\n\r\nDisplay Retina con Force Touch<br><br>\r\n\r\n\r\nSensori<br>\r\n\r\nCardiofrequenzimetro<br>\r\n\r\nAccelerometro<br>\r\n\r\nGiroscopio<br>\r\n\r\nSensore di luce ambientale<br><br>\r\n\r\n\r\nConnettivita<br>\r\n\r\n\r\nWi-Fi (802.11b/g/n a 2,4GHz)<br>\r\n\r\nBluetooth 4.0<br><br>\r\n\r\n\r\nBatteria<br>\r\n\r\nFino a 18 ore di autonomia<br><br> \r\n\r\n\r\nResistenza all''acqua<br>\r\n\r\nSi\r\n', 369.99, 'tv3-front.jpg', 'tv3-back.jpg', 'tv3-side.jpg'),
(2, 'Samsung Galaxy View 18.4" LTE', 'white', 'Processore OctaCore 1.6 GHz<br>\r\nDisplay 18.4” TFT, 1920x1080 Full HD<br>\r\nSistema Operativo AndroidTM 5.1 (Lollipop)<br>\r\nMemoria interna 32GB (espandibile fino a 128GB)<br>\r\nInternet TV\r\n', '\r\nDisplay<br>\r\n\r\n\r\n9.7" TFT,1024x768 (4:3) <br><br>\r\n\r\n\r\nProcessore<br>\r\n\r\n\r\nSnapdragon 410 QuadCore da 1.2 GHz <br><br>\r\n\r\n\r\n\r\nMemoria<br>\r\n\r\n\r\nInterna 16GB (espandibile fino a 128GB), 2GB di Ram <br><br>\r\n\r\n\r\n\r\nTecnologia<br>\r\n\r\n\r\nLTE/HSDPA/HSUPA <br><br>\r\n\r\n\r\n\r\nConnettivita<br>\r\n\r\n\r\nWi-Fi 802.11 a/b/g/n - Bluetooth 4.0 - micro USB <br><br>\r\n\r\n\r\n\r\nSistemaOperativo<br>\r\n\r\n\r\nAndroid™ 5.0.2 <br><br>\r\n\r\n\r\n\r\nApplicazioni<br>\r\n\r\n\r\nAndroid Market, Google Mobile App, Youtube, Inserimento testo e ricerca vocale, E-mail, A-GPS, SMS/MMS <br><br>\r\n\r\n\r\nFotocamera<br>\r\n\r\n\r\nFront: 2 Mpxl - Back: 5 Mpxl <br><br>\r\n\r\n\r\n\r\nLettore Multimediale<br>\r\n\r\n\r\naac,amr,awb,mp3,ogg,wav, DivX, XviD, MPEG4, VP8, H.263, H.264 <br><br>\r\n\r\n\r\n\r\nDimensioni<br>\r\n\r\n\r\n242,5 x 166,8 x 7,4 mm <br><br>\r\n\r\n\r\n\r\nPeso<br>\r\n\r\n\r\n455 grammi <br><br>\r\n\r\n\r\n\r\nAutonomia<br>\r\n\r\n\r\nStand-by fino a 250h - 43 ore in chiamata <br><br>\r\n\r\n\r\n\r\nIn dotazione<br>\r\n\r\n\r\nCarica batteria - Manuale d''uso - Cavo dati USB\r\n', 999.99, 'tv2-front.jpg', 'tv2-side.jpg', 'tv2-back.jpg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
